spring:
  threads:
    virtual:
      enabled: true
  application:
    name: qikserve
  datasource:
    url: jdbc:h2:mem:payment-ms
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

api:
  products:
    base-url: http://localhost:8081
